[package]
name = "slr"
version = "0.1.0"
authors = ["amlo <xplzjwz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grammar = { path = "../grammar" }
bit-set = "0.5.2"
indexmap = "1.6.0"
